theme: jekyll-theme-hacker
title: Aukkawut Ammartayakun
description: My webpage
navbar-links:
  About Me: "about-me"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
markdown: kramdown
kramdown:
    math_engine: katex
